---
title: "format_data"
author: "Dan Weinberger"
date: "5/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(reshape2)
```

```{r}
# a1 <-read_excel("./Data/A148_scope_2021_05_19.xlsx", skip=19)
# a2 <-read_excel("./Data/A149_scope_2021_05_19.xlsx", skip=19)
# a3 <-read_excel("./Data/A150_scope_2021_05_24.xlsx", skip=19)
# a4 <-read_excel("./Data/A147-A148_2021_05_24.xlsx", skip=19)

a1 <-read_excel('./Data/SCOPE_Master_20210108.xlsx', sheet='COM SAL')

a1$lytA[is.na(a1$lytA)] <- 45
a1$piaB[is.na(a1$piaB)] <- 45

a1$`lyta Repeated`[is.na(a1$`lyta Repeated`) & !is.na(a1$`DNA Date repeat`)] <- 45

a1$`piaB repeated`[is.na(a1$`piaB repeated`) & !is.na(a1$`DNA Date repeat`)] <- 45

a1$pos.initial <- a1$lytA<45 & a1$piaB<45
a1$pos.repeat <- a1$`lyta Repeated`<45 & a1$`piaB repeated`<45

a1$pos.both <- a1$pos.initial
a1$pos.both[a1$pos.repeat==0 & a1$pos.initial==1] <- 0

a1 <- a1[!is.na(a1$`DNA date`),] # only keep row if DNA has been extracted

b1 <- a1[c("Household #",'timeline','dw_id_full','pos.both')]
names(b1) <- c('hh','timeline','full_id','pos')
b1$full_id <- sub("\\.[0-9]+$", "", b1$full_id)


```

```{r}
plot(a1$lytA,a1$piaB)
plot(a1$`lyta Repeated`,a1$`piaB repeated`)
plot(a1$`lyta Repeated`,a1$lytA)

plot(a1$`piaB repeated`,a1$piaB)

```


```{r}
b1.m <- melt(b1, id.vars=c('hh','timeline','full_id'))

b1.c <- acast(b1.m, timeline~hh~full_id, fill=NA)

```



