---
title: "format_data"
author: "Dan Weinberger"
date: "5/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(reshape2)
library(dplyr)
library(stringr)

library(pheatmap)
library(RColorBrewer)
library(cowplot)
library(gridExtra)
library(ggplotify)
library(patchwork)
source('heat.fun.R')

```


ID 6.1 Saliva was very low under 100 ul.

ID 5.6 qpcr LytA -piaB was ran in plate A155_scope_2021_06_02 .The issue was the label: FIXED 5.5 to 5.6

ID 12.4 qPCR LytA -piaB was ran in plate A150_scope_2021_05_24.The issue was the label --FIXED 12.3 to 12.4

ID 62.2,63.2 samples were picked up 1 month after .We didn’t see any growth after incubation 37 degree over night 

ID 20.5 - 21.5 to verify


```{r}
 key1 <- read.csv('./Data/hh_id_key.csv')

key2 <- cbind.data.frame('id'=c(100,101) , 'Household'=c(51,51) )

key1 <- bind_rows(key1,key2)
file_list <- list.files(path="./Data/cleaned")
  
 all.res <-
   lapply(file_list, function(x){
     print(x)
     ds <- read_excel(paste0("./Data/cleaned/",x), skip=19)
     ds$expt <- substr(x,1,4)
     ds$Sample <- as.character(ds$Sample)
     ds$Target <- as.character(ds$Target)
     ds$Cq <- as.numeric(as.character(ds$Cq))
     cols.keep <- 
       c('Cq','Sample','Target','Content','expt','Biological Set Name')
     ds.names <- names(ds)
     ds.names <- intersect(ds.names,cols.keep)
    ds <- ds[,ds.names]
     return(ds)
   })
 

all.res <- lapply(1:length(all.res), function(x){ all.res[[x]]$plate= x 
return(all.res[[x]])
}) 


test1 <- lapply(all.res, function(x)  is.character(x$Target))

b1 <- bind_rows(all.res) 

b1$Target[is.na(b1$Target)] <- 
  b1$`Biological Set Name`[is.na(b1$Target)]

b1 <- b1[b1$Content!='Std',]

b1$Target <- gsub(' ' ,'', b1$Target, fixed=T)

b1$Target <- tolower(b1$Target)

b1$Target[b1$Target=='lyta_sso'] <- 'lyta'
b1$Target[b1$Target=='piab_sso'] <- 'piab'


#b1$Sample[is.na(b1$Sample)] <- b1$`sample id`[is.na(b1$Sample)]

b1 <-b1[!is.na(b1$Sample),]

b1$Sample <- round(as.numeric(b1$Sample),1)

b1 <- b1[b1$Sample>0 & !is.na(b1$Sample),]

c1 <- b1[, c('Sample','Cq','Target','plate')]

c1$Cq[is.na(c1$Cq)] <- 45

c1.m <- reshape2::melt(c1, id.vars= c('Sample','Target','plate'))

c1.c <- reshape2::dcast(c1.m, Sample+plate +variable ~ Target, fun.aggregate = min)

c1.c$pos <- c1.c$lyta<40 & c1.c$piab<40

write.csv(c1.c, './Data/cleaned_file.csv')



```

```{r, fig.width=5, fig.height=5}
plot(c1.c$lyta, c1.c$piab, xlim= c(45,0), ylim=c(45,0), xlab='lytA', ylab='piaB', bty='l')
abline(a=0, b=1)
abline(h=40, v=40, col='gray', lty=2)
```


```{r}

c1.m$ID <- sub("\\.[0-9]+$", "", c1.m$Sample)
c1.m$ID <- as.numeric(as.character(c1.m$ID))
c1.m$time <- sub('.*\\.', '', c1.m$Sample)

c1.m <- c1.m[order(c1.m$ID, c1.m$time),]
c1.m <- merge(c1.m, key1, by.x='ID',by.y='id')

d1 <- dcast(c1.m[,c('ID','Target','time','value')],  ID +Target ~ time, fun.aggregate = min, na.rm=T)

write.csv(d1, './Data/Result1.csv')

d1.alt <- dcast(c1.m[,c('ID','Target','time','value')],  ID +time~ Target, fun.aggregate = min, na.rm=T)

d1.alt <- d1.alt[!(d1.alt$ID %in% c(38,39)),] #these IDs were not included in study

write.csv(d1.alt, './Data/Result2.csv') #Anne's preferred format

c1.m <- c1.m[!(c1.m$ID %in% c(38,39)),] #these IDs were not included in study

d1.a <- acast(c1.m[,c('ID','Target','time','value','Household')], Target ~ ID +Household ~ time, fun.aggregate=min, na.rm=T, fill=9999)


```

## Heatmaps
```{r, fig.width=4, fig.height=8}
piab.plot <- heat.fun(target='piab')
lyta.plot <- heat.fun(target='lyta')

```
## Summary stats
```{r}
c1.m.m <- melt(c1.m[,c('Target','ID','Sample','value','Household') ],
                     id.vars=c('Target','ID','Sample','Household')) 
                     
c1.m.c <- dcast(c1.m.m, ID + Household + Sample  ~Target, fun.aggregate = min, fill=999)

#N people
length(unique(c1.m.c$ID))

#N households
length(unique(c1.m.c$Household))


#N samples
length(unique(c1.m.summary$Sample[c1.m$Target=='piab']))
length(unique(c1.m.summary$Sample[c1.m$Target=='lyta']))

#N positive
sum(c1.m.c$piab<40 )

#% positive
sum(c1.m.c$piab<40 )/nrow(c1.m.c)

#N positive lytA
sum(c1.m.c$lyta<40 )

sum(c1.m.c$lyta<40 )/nrow(c1.m.c)


#Count N people with piaB positives by IDs
c1.m.spl.id <- split(c1.m.c, c1.m.c$ID)
sum(sapply(c1.m.spl.id, function(x){
  min(x$piab) <40 
}
  ))

#Count N HH with piab positives by IDs
c1.m.spl.id <- split(c1.m.c, c1.m.c$Household)
sum(sapply(c1.m.spl.id, function(x){
  min(x$piab) <40 
}
  ))


```

